### PR TITLE
Dash nlp

### LINKED ISSUE #27: NLP

### PR DESCRIPTION
**Pull request by apberesford**
Visit App: https://dash5-services.plotly.host/dash-nlp-41/ 
Closes #27 
Screenshot 2024-04-05 at 3 43 19 PM
Screenshot 2024-04-05 at 3 43 28 PM
Screenshot 2024-04-05 at 3 43 35 PM

### CODE REVIEW

**Comment by jingningzhang1** [comment]
404 for me @apberesford. Do you mind adding me to the app?
image

**Comment by apberesford** [comment]
> 404 for me @apberesford. Do you mind adding me to the app? image

Oops sorry @jingningzhang1, Friday afternoon brain. I just added your access.

**Comment by jingningzhang1** [comment]
all good, looks great @apberesford! One thing ---- it appears that some padding disappeared with the new version. Is that easily fixable? Otherwise, the app functions well!
image

**Comment by apberesford** [comment]
Good catch, thanks @jingningzhang1. I also noticed that there was a loading issue around the date slider, which should be corrected now. Feel free to take another look!

**Comment by jingningzhang1** [comment]
cool looks good! can we remove this underline easily? if it's tricky, not a big deal
image

**Comment by apberesford** [comment]
All right I think we should be all set. Thanks @jingningzhang1 
Screenshot 2024-04-09 at 11 06 56 AM

**Pull request merged**
